config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'events#index'

  resources :checkins, only: [:new, :create]
  resources :events, only: [:index, :new, :create, :show] do
    resources :leagues, only: [:index, :new, :create, :show], controller: 'events/leagues' do
      resources :people, only: [:new, :create], controller: 'events/leagues/people'
    end
    resources :checkins, only: [:new, :create], controller: 'events/checkins'
  end
  resources :leagues, only: [:index, :show]
  resources :people, only: [:new, :create, :show]
end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  # == Associations
  belongs_to :person
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  # == Associations
  has_many :checkins
  has_many :people, -> { distinct }, through: :checkins
  has_many :event_leagues
  has_many :leagues, through: :event_leagues

  # == Scope methods
  default_scope { order(created_at: :asc) }
end

app/models/event_league.rb
class EventLeague < ActiveRecord::Base
  # == Associations
  belongs_to :event
  belongs_to :league
end

app/models/league.rb
class League < ActiveRecord::Base
  # == Associations
  has_many :event_leagues
  has_many :events, through: :event_leagues
  has_many :league_people
  has_many :people, through: :league_people
end

app/models/league_person.rb
class LeaguePerson < ActiveRecord::Base
  # == Associations
  belongs_to :league
  belongs_to :person
end

app/models/location.rb
class Location < ActiveRecord::Base
  # == Associations
  has_many :user_location_joins
  has_many :users, through: :user_location_joins
end

app/models/person.rb
class Person < ActiveRecord::Base
  # == Associations
  has_many :checkins
  has_many :user_person_joins
  has_many :users, through: :user_person_joins
  has_many :league_people
  has_many :leagues, through: :league_people

  # == Instance methods
  def up_by(event = nil)
    return attributes['up_by'] unless event

    checkins_from_event = event.checkins.where(person: self).order(:created_at)
    first_checkin = checkins_from_event.first
    last_checkin = checkins_from_event.last
    if last_checkin == first_checkin
      nil
    else
      last_checkin.weight - first_checkin.weight
    end
  end

  def percentage_change(event = nil)
    return unless up_by(event)

    starting_weight ? up_by(event).to_f / starting_weight * 100 : nil
  end

  def checkin_diffs
    grouped = checkins.includes(:event)
                      .order('events.created_at')
                      .group_by(&:event)
    event_diffs = {}
    grouped.each_pair do |event, event_checkins|
      diffs = event_checkins.sort_by(&:created_at).map(&:delta).compact
      event_diffs[event.try(:name)] = diffs.map { |d| format('%.2f', d) }
    end

    event_diffs
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # == Devise setup
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # == Associations
  has_many :user_person_joins
  has_many :people, through: :user_person_joins
  has_many :user_location_joins
  has_many :locations, through: :user_location_joins
end

app/models/user_location_join.rb
class UserLocationJoin < ActiveRecord::Base
  # == Associations
  belongs_to :user
  belongs_to :location
end

app/models/user_person_join.rb
class UserPersonJoin < ActiveRecord::Base
  # == Associations
  belongs_to :user
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events/base_controller.rb
module Events
  class BaseController < ApplicationController
    before_action :set_event

    def set_event
      @event = Event.find params[:event_id]
    end
  end
end

app/controllers/events/checkins_controller.rb
module Events
  class CheckinsController < Events::BaseController
    def new
      @checkin = @event.checkins.new
    end

    def create
      person = Person.find(checkin_params[:person_id])
      @checkin = CreateCheckin.call(person,
                                    @event,
                                    checkin_params[:weight].to_f,
                                    current_user)

      redirect_to event_path(@event)
    rescue StandardError
      flash[:error] = 'Please fill out all fields'
      redirect_to new_event_checkin_path(@event)
    end

    private

    def checkin_params
      params.require(:checkin).permit(:weight, :person_id)
    end
  end
end

app/controllers/events/leagues/people_controller.rb
module Events
  module Leagues
    class PeopleController < Events::LeaguesController
      before_action :set_league

      def new
        @person = @league.people.new
      end

      def create
        @person = Person.find params[:person_id]
        @league.people << @person

        redirect_to event_leagues_path(@event)
      end

      private

      def set_league
        @league = League.find params[:league_id]
      end
    end
  end
end

app/controllers/events/leagues_controller.rb
module Events
  class LeaguesController < Events::BaseController
    def index
      @leagues = @event.leagues
    end

    def show
      @league = @event.leagues.find params[:id]
    end

    def new
      @league = @event.leagues.new
    end

    def create
      @league = League.create(league_params)
      @league.events << @event

      redirect_to event_leagues_path(@event)
    end

    private

    def league_params
      params.require(:league).permit(:name)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find params[:id]
  end

  def create
    @event = Event.create(event_params)

    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :tagline)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all
  end

  def show
    @league = League.find params[:id]
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def create
    @location = Location.create(location_params)

    redirect_to new_checkin_path
  end

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  private

  def location_params
    params.required(:location).permit([:name])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person = Person.new
  end

  def create
    @person = Person.create(person_params)

    redirect_to root_path
  end

  def show
    @person = Person.find params[:id]
  end

  private

  def person_params
    params.required(:person).permit([:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/checkins/new.haml
%h1{ class: 'text-center' }= "New Checkin for #{@event.name}"
%br
- flash.each do |key, value|
  .alert{ class: "alert-#{key}" }
    %button.close{ data: { dismiss: 'alert' } } x
    %strong
      = value
%div
  .input-group
    = form_for :checkin, url: event_checkins_path do |f|
      - options = ['SELECT YOUR NAME'] + Person.all.map { |person| [person.name, person.id] }
      = f.select :person_id, options_for_select(options, disabled: ['-'*20]), class: 'input-block-level'
      %br
      = link_to('Not Listed?', new_person_path, class: 'btn btn-default btn-block') unless ENV['QUIET_MODE']
      %br
      = f.label :weight
      %br
      = f.text_field :weight, placeholder: 'Enter your weight', value: '', class: 'form-control'
      = f.submit class: 'btn btn-primary text-uppercase btn-block', value: 'SAVE >'

%h3
  %a= link_to('< Back', event_path(@event), class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/events/index.haml
%h1{ class: 'text-center' }= 'Events List:'
%br
%div{ class: 'table-container' }
  %table{ border: 0, class: 'table table-condensed borderless' }
    %tr
      %th{ class: 'ordinal' }
      %th{ class: 'text-left person-name' } NAME
      %th{ class: 'text-left person-name' }
      %th{ class: 'text-left person-name' } # PARTICIPANTS
    - @events.each_with_index do |event, index|
      %tr
        %td{ class: 'ordinal' }= index
        %td{ class: 'text-left weight' }= link_to(event.name, event_path(event.id))
        %td{ class: 'text-left weight' }
        %td{ class: 'text-left weight' }= event.people.count

.actions
  = link_to('CREATE NEW EVENT', new_event_path)
  |
  = link_to('LEAGUES LIST', leagues_path)

app/views/events/leagues/index.haml
%h1{ class: 'text-center' }= "#{@event.name}'s event leagues:"
%br
%div{ class: 'table-container' }
  %table{ border: 0, class: 'table table-condensed borderless' }
    %tr
      %th{ class: 'ordinal' }
      %th{ class: 'text-left person-name'} NAME
      %th{ class: 'text-left person-name'} # PARTICIPANTS
      %th{ class: 'person-name'}
    - @leagues.each_with_index do |league, index|
      %tr
        %td{class: 'ordinal'}= index
        %td{class: "text-left weight"}=link_to(league.name, event_league_path(@event, league))
        %td{class: "text-left weight"}=league.people.count
        %td{class: "text-left weight"}=link_to('Add participant', new_event_league_person_path(@event, league))

.actions
  = link_to('EVENT', event_path(@event))
  |
  = link_to('NEW LEAGUE', new_event_league_path(@event))

app/views/events/leagues/new.haml
%h1{ class: 'text-center' }= "New league for #{@event.name}"
%br
- flash.each do |key, value|
  .alert{ class: "alert-#{key}" }
    %button.close{ data: { dismiss: 'alert' } } x
    %strong
      = value
%div
  .input-group
    = form_for :league, url: event_leagues_path do |f|
      %p
      = f.label :name
      %br
      = f.text_field :name, { autocomplete: :off, class: 'form-control' }
      %br
      = f.submit class: 'btn btn-primary text-uppercase btn-block', value: 'SAVE >'

%h3
  %a= link_to('< Back', event_leagues_path(@event), class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/events/leagues/people/new.haml
%h1{class: 'text-center'} New Participant
%div

- flash.each do |key, value|
  .alert{ :class => "alert-#{key}" }
    %button.close{ :data => { :dismiss => "alert" } } x
    %strong
      = value
%div
  .input-group
    = form_tag event_league_people_path do
      - options = ['SELECT YOUR NAME'] + Person.all.map { |person| [person.name, person.id] }
      = select_tag :person_id, options_for_select(options, disabled: ['-'*20]), class: 'input-block-level'
      %br
      = link_to('Not Listed?', new_person_path, class: 'btn btn-default btn-block') unless ENV['QUIET_MODE']
      %br
      = submit_tag 'SAVE >', class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'

%h3
  %a= link_to('< Back', event_leagues_path(@event), class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/events/leagues/show.haml
%h1{ class: 'text-center' }= "WEIGH-IN #{@event.name} for #{@league.name}"
%h2{ class: 'text-center' }= @event.tagline
%div{ class: 'table-container' }
  %table{ border: 0, class: 'table table-condensed borderless' }
    %tr
      %th{ class: 'ordinal' }
      %th{ class: 'text-left person-name' } NAME
      %th{ 'data-field' => 'up_by', 'data-sortable' => 'true', class: 'text-right weight' } UP BY
    - previous_score = nil
    - people_with_current_rank = 1
    - @league.people.sort_by{ |p| p.up_by(@event) || -1000 }.reverse.each_with_index do |person, index|
      - up_by = person.up_by(@event)
      - positive = up_by.to_f > 0 ? 'positive' : 'negative'
      %tr
        - percentage_change = person.try(:percentage_change, @event)
        - if up_by.to_f == previous_score.to_f
          - people_with_current_rank += 1
        - else
          - index += people_with_current_rank
          - people_with_current_rank = 1
        - previous_score = up_by
        %td{ class: 'ordinal' }= up_by ? index : nil
        %td{ class: 'person-name' }= link_to(person.name.upcase, person_path(person))
        - percent_text = up_by && percentage_change ? "(#{percentage_change.round(2)}%)" : ""
        %td{ class: "#{positive} text-right weight" }= "#{up_by.try(:round, 3)} #{percent_text}"

.actions
  = link_to('EVENT', event_path(@event))
  |
  = link_to('EVENT LEAGUES', event_leagues_path(@event))

app/views/events/new.haml
%h1{class: 'text-center'} Please create a New Event
%div

- flash.each do |key, value|
  .alert{ :class => "alert-#{key}" }
    %button.close{ :data => { :dismiss => "alert" } } x
    %strong
      = value
%div
  .input-group
    = form_for :event, url: events_path do |f|
      %p
      = f.label :name
      %br
      = f.text_field :name, { autocomplete: :off, class: "form-control" }
      %p
      = f.label :tagline
      %br
      = f.text_field :tagline, { autocomplete: :off, class: "form-control" }
      = f.submit class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'

%h3
  %a= link_to('< Back', people_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/events/show.haml
%h2
  #{@event.name}
- @event.people.each_with_index do |person, index|
  %table
    %tr
      %td{class: 'ordinal'}= index
      %td{class: "text-left"}=link_to(person.name, person_path(person.id))
      %td{class: "text-left weight"}=person.up_by(@event)
  %br
%br
%br
%br
%br
%br
%h3
  %a= link_to('< Back', people_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <title>EAT TO COMPETE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=yes">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> -->
</head>
<body>
  <div class="container text-uppercase">
    <%= yield %>
  </div>
</body>
</html>

app/views/leagues/index.haml
%h1{ class: 'text-center' }= 'Leagues list:'
%br
%div{ class: 'table-container' }
  %table{ border: 0, class: 'table table-condensed borderless' }
    %tr
      %th{ class: 'ordinal' }
      %th{ class: 'text-left person-name' } NAME
      %th{ class: 'person-name'}
      %th{ class: 'text-left person-name' } # PARTICIPANTS
    - @leagues.each_with_index do |league, index|
      %tr
        %td{ class: 'ordinal' }= index
        %td{ class: 'text-left weight' }= link_to(league.name, league_path(league))
        %td{ class: 'text-left weight' }
        %td{ class: 'text-left weight' }= league.people.count

.actions
  = link_to('EVENTS', root_path)

app/views/leagues/show.haml
%h1= "LEAGUE #{@league.name}"
%br
%h2 Participants
%br
- @league.people.each_with_index do |person, index|
  %table
    %tr
      %td{ class: 'ordinal' }= index
      %td{ class: 'text-left' }= link_to(person.name, person_path(person.id))
  %br

.actions
  = link_to('LEAGUES LIST', leagues_path)
  |
  = link_to('EVENTS LIST', events_path)

app/views/locations/new.haml
%h1 New Location
.input-group
  = form_for :location, url: locations_path do |f|
    %p
    = f.label :name
    %br
    = f.text_field :name, { class: "form-control" }
    %p
    = f.submit class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'
%h3
  %a= link_to('< Back', new_checkin_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/locations/show.haml
%h2
  #{@location.name}
  %a= link_to('< Back', checkins_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/people/new.haml
%h1 New Person
.input-group
  = form_for :person, url: people_path do |f|
    %p
    = f.label :name
    %br
    = f.text_field :name, { class: "form-control" }
    %p
    = f.label :starting_weight
    %br
    = f.text_field :starting_weight, { autocomplete: :off, class: "form-control" }
    %br
    = f.submit class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'
%h3
  %a= link_to('< Back', :back, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/people/show.haml
%h2 #{@person.name}
%br
- @person.try(:checkin_diffs).each_pair do |event, diffs|
  %table
    %th= event
    - diffs.each do |diff|
      - classname = diff.to_f > 0 ? 'positive' : 'negative'
      %tr
        %td{ class: classname } #{diff.to_f}
  %br

.actions
  %h3
    %a= link_to('< Back', :back, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')